# Use 64-bit ARM Python slim image
From python:3.11-slim


# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your backend code
COPY . .

# Expose the FastAPI port
EXPOSE 8000

# Run the app using python main.py
CMD ["python", "main.py"]